name: Semantic Release

on:
  push:
    branches: [
      "main",
      "beta"
    ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: | 
          npm install
          npm run build --if-present
          npm test
      - name: Create Release Tag
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'master',
              'main',
              'next',
              'next-major',
              {
                name: 'beta',
                prerelease: true
              },
              
            ]
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Create a GitHub release
      #   uses: actions/create-release@v1
      #   with:
      #     tag_name: ${{ steps.semantic.outputs.new_release_version }}
      #     release_name: Release ${{ steps.semantic.outputs.new_release_version }}
      #     # body: ${{steps.semantic.outputs.changelog}}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}